## Векторы

In [1]:
import numpy as np

In [2]:
s=np.array([33, 65, 50, 45])

In [3]:
s

array([33, 65, 50, 45])

In [4]:
s[2]

50

In [5]:
len(s)

4

In [8]:
s.shape

(4,)

### Покупаем квартиру

Чтобы иметь возможность математически или даже программно оперировать сущностями нашего мира, нам нужно их упростить до формы понятной компьютеру. Признаковое описание объектов реального мира в виде чисел — это и есть то самое упрощение.

Анализируя потенциальную стоимость определенной новой квартиры, мы будем иметь в виду следующие признаки:

        общая площадь квартиры в квадратных метрах,
        этаж квартиры,
        количество комнат,
        цена квартиры за квадратный метр,
        количество подъездов в доме.


Рассмотрим предложение на покупку

На рынке новостроек появилось предложение от застройщика "Гарантия" — двухкомнатная квартира общей площадью 59.50 кв.м, жилой площадью 31.40 кв.м на 19-м этаже 22-х этажного дома. В доме 2 подъезда. Цена за квадратный метр квартиры у этого застройщика составляет 60550 рублей.

In [9]:
apartment = np.array([59.50, 31.40, 19, 2, 60550, 2])

Эта последовательность чисел и называется вектором. Вектор характеризует конкретный объект — конкретную квартиру. А число в той или иной позиции вектора описывает конкретный признак объекта. То есть вектор — это, по сути, одномерный массив: 

In [11]:
print("ndim:", apartment.ndim) # число осей (измерений) массива - n.dim: 1
print("shape:", apartment.shape) # размеры массива, для вектора определена только длина - shape: (6, )

ndim: 1
shape: (6,)


Давайте, как настоящие исследователи данных, попробуем извлечь полезную информацию из вектора, при этом уменьшив его! 

Упростим себе задачу оценки новой квартиры — сгенерируем новый признак — отношение жилой площади к общей. А от старых признаков смело избавимся, сократив векторное пространство нашего объекта.

Для того, чтобы сгенерировать новый параметр share_living_space (доля жилой площади в квартире) из старых признаков, содержащихся в векторе-описании apartment нашей квартиры, нам необходимо вспомнить обращение к элементам массива. Разделим значение жилой площади на её общее количество:

In [12]:
# вычислим долю жилой площади в квартире
share_living_space = apartment[1]/apartment[0]

Избавимся от старых признаков, посредством функции delete(), которую предоставляет библиотека numpy. Передадим в значение функции индексы признаков, которые необходимо удалить из нашего массива apartment:

In [13]:
apartment = np.delete(apartment, [0, 1])

И в завершение добавим в конец нашего массива новый признак share_living_space, который сочетает в себе смысл двух старых признаков:

In [14]:
apartment = np.append(apartment, share_living_space)

In [18]:
apartment.shape

(5,)

Найти сумму и разность векторов

In [21]:
x = np.array([5, 2])
y = np.array([-5, -11])

In [22]:
x+y

array([ 0, -9])

In [23]:
x-y

array([10, 13])

Доходы Алексея за три месяца составили 120, 150 и 90 тысяч рублей, его жены: 130, 130 и 130 тысяч рублей, а тёщи: 2, 3 и 2.5 тысячи евро.

Найдите вектор доходов тёщи в тыс. рублей, если курс евро составляет 72 рубля.

In [25]:
z = np.array([2, 3, 2.5])
z = z*72
z

array([144., 216., 180.])

In [26]:
x = np.array([120, 150, 90])
y = np.array([130, 130, 130])

In [27]:
z + x + y

array([394., 496., 400.])

### Линейная комбинация векторов

In [30]:
x = np.array([4, 5])
y = np.array([2, 1])
z = np.array([1, 0])
#коэффициенты 2, -3, 5

In [31]:
x*2+y*-3+z*5

array([7, 7])

Юный предприниматель Вовочка мастерит ракеты на водном топливе и продает их. За 4 недели он смастерил 3, 4, 5 и 9 ракет, а продал 1, 5, 3 и 6 ракет соответственно.

In [32]:
x = np.array([3, 4, 5, 9])
y = np.array([1, 5, 3, 6])

На изготовление одной ракеты он тратит 200 рублей, а продаёт их по 400 рублей за штуку.

In [34]:
y*400-x*200

array([-200, 1200,  200,  600])

## Скалярное произведение векторов

Всего есть четыре основных способа умножить векторы:

                Скалярное произведение. Результат — число. 
                Векторное произведение. Результат — вектор.
                Смешанное произведение. Результат — число. 
                Тензорное произведение. Результат — матрица.

рисунок  Чтобы найти скалярное произведение двух векторов, необходимо перемножить их координаты с одинаковыми номерами и сложить то, что получится. 

Скалярное произведение векторов a и b обозначается как:
                                    (a,b)

В Python скалярное произведение векторов вычисляется при помощи команды ***np.dot.***

In [3]:
a = np.array([65,70,120,30])
w = np.array([0.4,0.4,0.2,0.8])

In [4]:
np.dot(a,w)

102.0

### Длина вектора

 Длина вектора вычисляется как квадратный корень из скалярного произведения вектора с самим собой. Для нас это это просто корень из суммы квадратов координат, как в теореме Пифагора — для случая с размерностью вектора равной двум (геометрически это длина отрезка).

sqrt((a,a)) = sqrt((a*a)+(a*a))

### Свойство скалярного произведения векторов (линейность)

Всем знакомо правило раскрытия скобок при умножении чисел:
    (a+b)(c+d) = ac + ad + bc + bd
    (5+7)(2+3) = 5 * 2 + 5 * 3 + 7 * 2 + 7 * 3

### Особый случай. Ортогональность векторов

Определение: Векторы a и b называются ортогональными, если их скалярное произведение равно нулю.

Найти скалярное произведение векторов:

In [5]:
x = np.array([4,5,-1])
y = np.array([2,0,1])
np.dot(x,y)

7

Длина вектора равна нулю, только если сам вектор нулевой 

Квадрат длины вектора равен его скалярному произведению с самим собой 

Найти длину вектора:

In [6]:
x = np.array([4,6,1])
(np.dot(x,x))**(1/2)

7.280109889280518

Проверка ортогональности:

In [8]:
x = np.array([4,5,-1])
y = np.array([0,0,0])
np.dot(x,y)

0

In [10]:
x = np.array([4,-1])
y = np.array([1,4])
np.dot(x,y)

0

### Практическая задача

Агентство «Рай в Шалаше» недавно сдало 4 квартиры в одном доме. Общая площадь квартир: 33, 42, 33 и 65 кв м. Жилая площадь: 24, 32, 20 и 48 кв м. Арендная плата: 39, 50, 38 и 77 тысяч рублей соответственно. В том же доме появилась новая квартира общей площадью 50 кв м, из которых жилая — 40 кв м. 
На основе имеющихся данных выберите оптимальную арендную плату для новой квартиры.

In [32]:
#Данные в векторном виде
x_all = np.array([33, 42, 33, 65])
x_live = np.array([24,32,20,48])
cost = np.array([39,50,38,77])

Нам нужно порекомендовать для новой квартиры оптимальную арендную плату, исходя из опыта предыдущих 4 квартир. Ключом к решению является линейная зависимость векторов: можно заметить, что вектор p линейно выражается через x_all и x_live

In [19]:
x_new_all = np.array([50])
x_new_live = np.array([40])

p = x_new_all + 1/4 * x_new_live = 50 + 1/4 * 40 = 60

In [20]:
x_new_all + 1/4*x_new_live

array([60.])

Так как новая квартира расположена в том же доме, что и первые четыре, она находится в тех же условиях, и оптимальную арендную плату выбрать несложно: нужно сложить общую и жилую площади с коэффициентами 1 и ¼. Как-то все слишком просто, не правда ли? Добавим к нашей задаче реальных условий.

***условие № 2***

Пусть во второй квартире обнаружились тараканы, и её пришлось сдать дешевле: за 48 460 рублей, а в первой и третьей квартирах был застекленный балкон, и их удалось сдать дороже: за 40 000 и за 39 000 рублей.
На основе имеющихся данных выберите оптимальную арендную плату для новой квартиры.

Теперь вектор арендной платы не выражается линейно через векторы площадей.

In [23]:
x_all_ = np.array([33,42,33,65])
x_live_ = np.array([24,32,20,48])
cost_ = np.array([40,48.46,39,77])

Векторы общей и жилой площади лежат в некоторой плоскости. Вектор p из первого условия задачи линейно выражается через них, а значит, лежит в той же плоскости. Вектор pреал выразить через векторы площадей уже нельзя, значит, он в этой плоскости не лежит.  

вектор n, как разница между pреал и p, символизирует влияние других факторов на стоимость аренды. Вычислим его координаты и найдём скалярное произведение с вектором p

In [35]:
cost = np.array([39,50,38,77])
cost_ = np.array([40,48.46,39,77])
n = cost_-cost
n

array([ 1.  , -1.54,  1.  ,  0.  ])

In [37]:
round(np.dot(cost, n))

0.0

Скалярное произведение равно нулю, это значит, что угол между векторами p и n равен 90 градусов. Таким образом, вектор p является ортогональной проекцией вектора pреал на плоскость.

Это значит, что среди всех возможных линейных комбинаций векторов общей и жилой площади наше изначальное p —  наилучший прогноз арендной платы. Другими словами, если другой информации нет, то 60 тысяч рублей, которые мы получили в первом условии задачи, и есть наш лучший прогноз стоимости аренды новой квартиры.

**Резюмируем**: мы построили простейшую линейную регрессию стоимости аренды квартиры на жилую и общую площадь по зашумлённым данным, представленным в векторе pреал.

Пусть появилась дополнительная информация — нежилая площадь. Позволит ли она улучшить прогноз по аренде новой квартиры?

Нежилая площадь является разностью общей и жилой, а значит, лежит в той же плоскости. А это значит, что проекция pреал на эту плоскость не поменяется, то есть и наилучший прогноз останется без изменений. 

Таким образом, линейные комбинации факторов не добавляют точности прогнозу, и, как мы увидим позже, сильно портят вычисления при построении линейных регрессий.

**Комментарий к заданию 1.6.2**. Длина вектора - число, которое ставится в соответствие каждому элементу векторного пространства. Оно у разных векторов может совпадать или различаться. При этом векторы имеют равное количество координат, потому что они из одного пространства определенной размерности. И операция сложения, заданная на пространстве, предполагает, что слагаемые имеют равное количество координат. Но они могут иметь как одну длину, так и различную.



***Практика***

In [4]:
a = np.array([1,2,3])
b = np.array([6,7,8])
c = np.array([1,0,1])

In [5]:
# вместо np.dot можно использовать @ для нахождения скалярного произведения
a@b 

44

In [6]:
#длина вектора
l = np.linalg.norm(a)
l

3.7416573867739413

In [7]:
#нормировка
a_norm = a/np.linalg.norm(a)
a_norm

array([0.26726124, 0.53452248, 0.80178373])

In [8]:
#lenth of norm
np.linalg.norm(a_norm)

1.0

Нормирование вектора — это получение вектора с тем же направлением, что и исходный, но нормой 1.

Норма вектора вычисляется как корень из суммы квадратов его компонент. Её физический смысл: норма показывает, насколько вектор «большой».

Длина вектора (в физическом смысле) — это то же, что и норма, применимо к векторам в реальном пространстве.

рис  Нормирование производится делением вектора на его норму.

### Задача 1. Условие

В Hut_Paradise_DF представлен фрагмент базы данных агенства «Рай в Шалаше». По строкам расположены квартиры, по столбцам — параметры: арендная плата, общая площадь, количество комнат, этаж, количество показов на две недели и жилая площадь:

In [10]:
import pandas as pd

In [11]:
Hut_Paradise_DF = pd.DataFrame({'1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
                                '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
                                '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
                                '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
                                '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
                                '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]})

Найдите вектор параметров квартиры номер 5:

In [14]:
np.array(Hut_Paradise_DF.loc[4])

array([40, 33,  1,  6, 20, 16])

Найдите вектор этажей всех квартир:

In [17]:
np.array(Hut_Paradise_DF['4.Floor'])

array([ 5, 12, 10,  3,  6, 13,  8, 21,  5])

На каком этаже расположена квартира номер 3? 

In [18]:
Hut_Paradise_DF['4.Floor'].loc[2]

10

Найдите количество квартир:

In [19]:
len(Hut_Paradise_DF)

9

Вычислите вектор нежилой площади:

In [21]:
np.array(Hut_Paradise_DF['2.Area']) - np.array(Hut_Paradise_DF['6.Liv.Area'])

array([13, 12, 15, 13, 17,  9, 20, 15, 25])

Арендная плата измеряется в тысячах рублей. Пересчитайте стоимость аренды каждой квартиры в тысячах гривен, если курс 10 руб = 4 гривны:

In [22]:
(np.array(Hut_Paradise_DF['1.Rent']) / 10) * 4

array([26., 28., 48., 14., 16., 20., 40., 36., 34.])

Пусть в первой квартире один просмотр занимает 10 минут, во второй — 20 минут, в третьей — полчаса, в четверой — 15 минут, в пятой — 5 минут, в шестой — 40 минут, в седьмой — 20 минут, в восьмой — 8 минут и в девятой — 20 минут. Найдите продолжительность просмотров в минутах во всех квартирах за 2 недели:

In [23]:
view_time = np.array([10,20,30,15,5,40,20,8,20])
sum(np.array(Hut_Paradise_DF['5.Demo two weeks']) * view_time)

1348

### Задача 2. Условие

Даны три вектора:

In [24]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])

Проверьте, являются ли векторы попарно ортогональными.

Составьте линейную комбинацию векторов v и w с коэффициентами 2 и -3:

In [26]:
lin_comb = v*2+w*-3
lin_comb

array([-3, 14,  3,  4,  2])

Будет ли эта комбинация ортогональна вектору u?

In [27]:
np.dot(lin_comb,u)

0

Ответ: да

Нормируйте векторы u, v, w.

In [28]:
u_norm = u/np.linalg.norm(u)
v_norm = v/np.linalg.norm(v)
w_norm = w/np.linalg.norm(w)

In [33]:
print(u_norm)
print(round(u_norm[2],3))

[0.8660254  0.         0.28867513 0.28867513 0.28867513]
0.289


In [34]:
print(v_norm)
print(round(v_norm[3], 3))

[ 0.          0.33333333  0.          0.66666667 -0.66666667]
0.667


In [35]:
print(w_norm)
print(round(w_norm[0], 3))

[ 0.21320072 -0.85280287 -0.21320072  0.         -0.42640143]
0.213


# Матрицы

Матрица представляет собой набор чисел, расположенных по строкам и столбцам, как в таблице.

Найти сумму матриц:

In [37]:
a = np.array([[1,1], [5,7]])
b = np.array([[6,1], [-5,5]])
a+b

array([[ 7,  2],
       [ 0, 12]])

Транспонирование мартицы:

In [38]:
r = np.array([[1,5,4],[0,1,0]])
r.T

array([[1, 0],
       [5, 1],
       [4, 0]])

Диагональная матрица является инвариантом транспонирования. 
Если вычесть из квадратной матрицы единичную, поменяется только главная диагональ.
Все столбцы диагональной матрицы ортогональны друг другу. 

### Задача. Условие

Данные по доходам и расходам каждого члена семьи Ивановых записаны в одномерные массивы NumPy

In [39]:
import numpy as np

Husband_Income = np.array([100,220,140])
Wife_Income = np.array([150,200,130])
Mother_In_Law_Income = np.array([90,80,100])

Husband_Сonsumption = np.array([50,50,60])
Wife_Сonsumption = np.array([100,80,140])
Mother_In_Law_Сonsumption = np.array([100,20,140])

Составьте матрицу Inc доходов семьи, расположив доходы мужа, жены и тещи в первый, второй и третий столбцы.

In [44]:
Inc = np.array([Husband_Income, Wife_Income, Mother_In_Law_Income])
Inc = Inc.T
Inc

array([[100, 150,  90],
       [220, 200,  80],
       [140, 130, 100]])

Составьте матрицу Cons расходов семьи, расположив расходы мужа, жены и тещи в первый, второй и третий столбцы.

In [45]:
Cons = np.array([Husband_Сonsumption, Wife_Сonsumption, Mother_In_Law_Сonsumption])
Cons = Cons.T
Cons

array([[ 50, 100, 100],
       [ 50,  80,  20],
       [ 60, 140, 140]])

Доходы представлены до уплаты налогов. Налоговая ставка - 13%. Вычислите матрицу доходов семьи Ивановых после уплаты налогов.

In [48]:
Inc_tax = Inc - (Inc * 0.13)
Inc_tax

array([[ 87. , 130.5,  78.3],
       [191.4, 174. ,  69.6],
       [121.8, 113.1,  87. ]])

Вычислите матрицу P, которая покажет баланс семьи Ивановых за один месяц (то есть разницу между доходами и расходами)

In [49]:
Inc_tax - Cons

array([[ 37. ,  30.5, -21.7],
       [141.4,  94. ,  49.6],
       [ 61.8, -26.9, -53. ]])

Операция умножения двух матриц возможна только в том случае, если число столбцов в первой матрице равно числу строк во второй.

Если матрица A содержит m строк, а матрица B содержит n столбцов, то результатом их умножения будет матрица С размера  m × n.

 Умножение матриц некоммутативно, то есть  AB ≠ BA.

 Умножать вектор-строку на матрицу можно только слева.

Найти произведение матрицы:

In [52]:
a = np.array([[1,-1,2,4,0],
             [8,2,0,5,3],
             [0,1,2,1,2]])
b = np.array([[1,0,1,0],
             [0,0,2,-1],
             [1,0,1,1],
             [0,1,1,1],
             [1,1,0,-1]])
np.dot(a,b)

array([[ 3,  4,  5,  7],
       [11,  8, 17,  0],
       [ 4,  3,  5,  0]])

NxM * M*L = NxL

Найти тензорное произведение

In [60]:
a = np.array([1,3])
b = np.array([-3,1])
tensor = np.array([[a[0] * b[0], a[0] * b[1]],
                 [a[1] * b[0], a[1] * b[1]]])
tensor


array([[-3,  1],
       [-9,  3]])

- Нулевая и единичная матрица играют роль нуля и единицы в матричном умножении.
- Умножение на шаровую матрицу — то же самое, что умножение на скаляр.
- Умножение на диагональную матрицу даёт растяжение каждого столбца или строки в зависимости от порядка.
- Диагональные матрицы коммутируют между собой.

AB = BA, если Хотя бы одна из матриц шаровая u Обе матрицы диагональные 

In [64]:
a = np.array([[2,0],[0,3]])
b = np.array([[1,1],[4,5]])
np.dot(a,b)

array([[ 2,  2],
       [12, 15]])

In [65]:
np.dot(b,a)

array([[ 2,  3],
       [ 8, 15]])

Делители нуля — это специальные ненулевые элементы, которые дают ноль при умножении.

In [81]:
a = np.array([[2,-1],[-6,3]])
b = np.array([[2,5],[4,10]])
print(np.dot(a,b))
print(np.dot(b,a))

[[0 0]
 [0 0]]
[[-26  13]
 [-52  26]]


При транспонировании меняется порядок произведения:

(A*B).T = B.T A.T
(A*B*C).T = (BC).T * A.T = C.T B.T A.T

 Матрицей Грама системы векторов называется матрица, составленная из их скалярных произведений.

In [82]:
x = np.array([[1,1],[1,2],[0,-1]])

In [83]:
np.dot(x, x.T)

array([[ 2,  3, -1],
       [ 3,  5, -2],
       [-1, -2,  1]])

 Матрицей Грама системы векторов называется матрица, составленная из их скалярных произведений.

Oтметим, что матрица Грама системы векторов всегда имеет вещественные собственные числа и диагонализируется, а если векторы линейно независимы, то ещё и обратима. Этим мы будем пользоваться при построении и апгрейдах модели линейной регрессии.

рис   Матрицы Х и ХТ можно умножать в любом порядке. В обоих случаях получится симметричная квадратная матрица.

Найдите матрицу Грама G системы векторов

In [7]:
vectors = np.array([[1,1],
                   [2,-1],
                   [1,2]])

In [8]:
np.dot(vectors, vectors.T)

array([[2, 1, 3],
       [1, 5, 0],
       [3, 0, 5]])

- На главной диагонали матрицы Грама стоят квадраты длин векторов 
- Нули в 3 строке и 3 столбце матрицы означают, что векторы b и c ортогональны 
- Столбцы матрицы линейно зависимы

### Задача 1. Условие

Даны матрица A и вектор x.

In [17]:
A = np.array([[5,-1,3,1,2],[-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])

Найдите произведение матрицы A и вектора x в том порядке, в котором их можно умножить.

In [18]:
np.dot(A,x)

array([26, 30])

### Задача 2. Условие

Даны две матрицы:

In [21]:
A = np.array([[1,9,8,5],[3,6,3,2],[3,3,3,3],[0,2,5,9],[4,4,1,2]])
B = np.array([[1,-1,0,1,1],[-2,0,2,-1,1]])

Найдите произведение матриц A и B в том порядке, в котором их можно умножить.

In [25]:
np.dot(A.T,B.T)

array([[  2,   8],
       [  9, -10],
       [ 11, -14],
       [ 14, -11]])

In [27]:
np.dot(B,A)

array([[  2,   9,  11,  14],
       [  8, -10, -14, -11]])

### Задача 3. Условие

Дана система векторов:

In [28]:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])

Найдите матрицу Грама системы векторов x,y,z

In [29]:
A = np.array([x,y,z])
np.dot(A,A.T)

array([[22,  3,  0],
       [ 3,  7,  0],
       [ 0,  0,  3]])

### Задача 4. Условие



В салоне красоты «Феи ножниц» работает 8 стилистов: Аня, Борис, Вика, Галя, Дима, Егор, Женя и Юра.

В dataframe Count_DF содержится информация по количеству услуг, оказанных каждым стилистом за апрель.

В dataframe Price_DF содержится информация по стоимости услуг у каждого стилиста в тысячах рублей.

In [31]:
import pandas as pd
Count_DF = pd.DataFrame({'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
                                'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
                                'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
                              'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
                                'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
                                }, 
                               index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])
Price_DF = pd.DataFrame({'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
                                'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
                                'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
                              'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
                                'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
                                }, 
                               index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра'])

In [32]:
Count_DF

Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня                 10                5           12       15    10
Борис                2               21            3       25     6
Вика                12               12            0       30     4
Галя                 4                8           18       14     5
Дима                 6               25           27       25    18
Егор                10                3            2       17    12
Женя                22                1            4       25    20
Юра                  7                0           31       31    28

In [33]:
Price_DF

Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня                2.0              1.5          1.0      0.8   1.0
Борис              1.8              2.5          1.0      1.0   1.0
Вика               2.0              2.0          0.0      0.5   2.0
Галя               1.8              1.2          2.8      0.8   2.0
Дима               2.5              3.5          2.0      1.0   1.5
Егор               5.0              5.0          3.0      2.0   2.5
Женя               1.1              1.0          1.5      0.5   1.7
Юра                4.5              4.0          2.5      1.0   2.0

Найдите вектор выручки Бориса

In [40]:
count_Boris = np.array(Count_DF.loc['Борис'])
price_Boris = np.array(Price_DF.loc['Борис'])

In [42]:
count_Boris * price_Boris

array([ 3.6, 52.5,  3. , 25. ,  6. ])

Найдите вектор прибыли салона по стилистам, если за каждую услугу стилисты платят определенную комиссию салону.

In [44]:
commission = np.array([0.2, 0.2, 0.3, 0.1, 0.1])

In [46]:
total_gain = np.array(Count_DF) * np.array(Price_DF)

In [52]:
sum((total_gain * commission).T)

array([11.3 , 15.22, 11.9 , 20.6 , 41.9 , 21.2 , 11.49, 38.25])

Найдите вектор прибыли стилистов

In [53]:
sum((total_gain - (total_gain * commission)).T)

array([ 50.2 ,  74.88,  59.1 ,  67.8 , 166.6 , 113.8 ,  66.21, 157.75])

# Обратная матрица

 Обратным к числу а называется такое число a -1, которое в произведении с a даст единицу

Например, для 2 обратным будет 0.5:  2 -1 = 0.5, т.к. 2 · 0.5 = 1.

Свойство: обратное число всегда одно и неважно, с какой стороны умножать на него.

Пример решения на python

In [55]:
A = np.array([[1,2,3],[4,5,6],[7,8,10]])

In [56]:
A

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 10]])

In [57]:
np.linalg.inv(A)

array([[-0.66666667, -1.33333333,  1.        ],
       [-0.66666667,  3.66666667, -2.        ],
       [ 1.        , -2.        ,  1.        ]])

In [65]:
x = np.array([[2,0,0],[0,4,0],[0,0,5]])

In [66]:
np.linalg.inv(x)

array([[0.5 , 0.  , 0.  ],
       [0.  , 0.25, 0.  ],
       [0.  , 0.  , 0.2 ]])

# Определитель матрицы

Определитель матрицы — это число, специальная числовая характеристика квадратных матриц, которая является своего рода мерой вырожденности матрицы и для размерности 2 × 2 вычисляется по следующему правилу:

det([a,b]  
    [c,d]) = ab-bc

В Python определитель считается командой linalg.det из библиотеки numpy

In [67]:
np.linalg.det(A)

-3.000000000000001

Свойства определителя:
    - det(E) = 1, det(diag(alpha1,...,alphan)) = alpha1 * ... * alphan
    - det(Beta*A) = Beta * det(A)
    - det(A.T) = det(A)
    - det(AB) = det(BA) = det(A)*det(B)
    - det(A^-1) = 1/det(A), if det(A) != 0

Вырожденность матрицы

Определение: Матрицы с нулевым определителем называются вырожденными.

Если det (A) = 0, то:
    - матрица А вырожденная;
    - у матрицы А не существует обратной;
    - столбцы и строки матрицы А линейно зависимы.

Найдите det(A), det(B), det(A+B), если 

In [68]:
A = np.array([[1,2],[1,1]])
B = np.array([[5,-2],[-1,4]])

In [69]:
np.linalg.det(A)

-1.0

In [70]:
np.linalg.det(B)

17.999999999999996

In [71]:
np.linalg.det(A+B)

29.99999999999999

Найдите det(A), det(A^-1) если 

In [72]:
A = np.array([[2,0,0],[0,1,0],[0,0,4]])

In [73]:
np.linalg.det(A)

7.999999999999998

In [74]:
np.linalg.det(np.linalg.inv(A))

0.12500000000000003

Квадратная матрица обязательно обратима, если:
    - Её столбцы линейно независимы 
    - Её определитель не равен нулю 

# Линейная (не)зависимость

Метод определения линейной зависимости/независимости при помощи СЛАУ(система линейных алгебраических уравнений):
    1. Записать СЛАУ в матричном виде и решить её
    2. Есть ненулевые решения - векторы линейно зависимы
    3. Нет ненулевых решений - векторы линейно независимы

### Как определить при помощи ранга, являются ли векторы линейно зависимыми

Ранг матрицы — количество линейно независимых столбцов.
Ранг системы векторов — размерность этой системы. 

После преобразований матрицы к ступенчатому виду ранг равен количеству ступенек.

Ранг системы векторов равен количеству линейно независимых векторов, т.е. размерности всей системы.

Чтобы исследовать систему векторов на линейную зависимость / независимость с помощью ранга, достаточно записать эти векторы в матрицу по столбцам и найти ранг полученной матрицы. Ранг будет равен количеству линейно независимых векторов в системе.

Базис — максимальная линейно независимая подсистема векторов.
В системе векторов можно выбрать ровно столько линейно независимых векторов, какой у нее ранг.
Базис матрицы — максимальная линейно независимая подсистема столбцов матрицы.

Базисов может быть несколько.

Для вычисления ранга матриц в библиотеке nupmy есть команда linalg.matrix_rank

In [76]:
v1 = np.array([1,2,3,1])
v2 = np.array([4,5,6,1])
v3 = np.array([7,8,9,1])
A = v1 = np.array([v1,v2,v3]).T

In [77]:
A

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9],
       [1, 1, 1]])

In [78]:
np.linalg.matrix_rank(A)

2

Мы видим, что ранг системы равен 2, а векторов в ней 3, значит, система линейно зависима. В качестве базиса можем взять любые два вектора.

Свойства ранга

    - Если  А — прямоугольная матрица размера m × k, то rk(A) ≤ min(m, k).
    - Если rk(A) = min(m, k), то А —матрица максимального ранга.
    - Квадратная матрица А размера n × n обратима, если:

            - det(A) ≠ 0
            - столбцы (или строки) матрицы А линейно независимы 
            - rk(A) = n

    - Квадратная матрица А размера n × n вырождена, если:

            - rk(A) < n
            - Чем меньше rk(A), тем более вырождена A

Для успешного построения регрессий необходимо научиться избавляться от линейной зависимости.

Пропорциональные вектроы в математике называются коллинеарными.
Напривет векторы (1,2,3) и (2,4,6) коллинеарны

- Коллинеарные векторы всегда линейно зависимы.
- Нулевой вектор коллинеарен любому вектору 

Определить зависимость векторов

In [82]:
a = np.array([4,0])
b = np.array([1,1])
c = np.array([6,4])
A = np.array([a,b,c])

In [83]:
A

array([[4, 0],
       [1, 1],
       [6, 4]])

In [84]:
np.linalg.matrix_rank(A)

2

Попарно линейно независимы (то есть каждая пара линейно независима) 

In [87]:
a = np.array([4,1,0])
b = np.array([-1,4,0])
c = np.array([0,0,1])
A = np.array([a,b,c]).T

In [88]:
A

array([[ 4, -1,  0],
       [ 1,  4,  0],
       [ 0,  0,  1]])

In [89]:
np.linalg.matrix_rank(A)

3

- Попарно ортогональны (то есть каждая пара ортогональна) 
- Попарно линейно независимы (то есть каждая пара неколлинеарна) 
- Линейно независимы в целом 

In [97]:
aa = np.array([1,0,3,5])
ba = np.array([0,4,5,5])
ca = np.array([0,0,0,0])
da = np.array([0,0,0,0])
A = np.array([aa,ba,ca,da])

In [98]:
ab = np.array([1,0,3,5])
bb = np.array([0,4,5,5])
cb = np.array([0,0,0,4])
db = np.array([0,0,0,0])
B = np.array([ab,bb,cb,db])

In [99]:
np.linalg.matrix_rank(A)

2

In [100]:
np.linalg.matrix_rank(B)

3

### Задача 1. Условие

Дана матрица А

In [101]:
A = np.array([[8, 6, 11], [7, 5, 9],[6, 10, 6]])

Найдите обратную матрицу к матрице А.

In [102]:
np.linalg.inv(A)

array([[-1.875  ,  2.3125 , -0.03125],
       [ 0.375  , -0.5625 ,  0.15625],
       [ 1.25   , -1.375  , -0.0625 ]])

### Задача 2. Условие

Дана система векторов:

In [103]:
v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])

Найдите ранг системы векторов v1, v2, v3, v4.

In [104]:
A = np.array([v1,v2,v3,v4])

In [105]:
np.linalg.matrix_rank(A)

4

Найдите матрицу Грама системы векторов v1, v2, v3, v4.

In [106]:
np.dot(A,A.T)

array([[360,  96,  73, -35],
       [ 96,  46,  16,   4],
       [ 73,  16,  33,   4],
       [-35,   4,   4,  51]])

Найдите определитель матрицы Грама системы v1, v2, v3, v4.

In [107]:
np.linalg.det(A@A.T)

3716647.9999999995

Является ли матрица Грама системы v1, v2, v3, v4 вырожденной?

нет так как определитель матрицы не равен нулю

Найдите обратную матрицу к матрице Грама системы v1, v2, v3, v4.

In [109]:
inv_Gramm = np.linalg.inv(A@A.T)

In [110]:
inv_Gramm

array([[ 0.01711488, -0.02798543, -0.02623063,  0.01599775],
       [-0.02798543,  0.071967  ,  0.03031441, -0.02722776],
       [-0.02623063,  0.03031441,  0.07683106, -0.02640498],
       [ 0.01599775, -0.02722776, -0.02640498,  0.03479318]])

In [115]:
round(inv_Gramm[2][0],3)

-0.026